# ----------------------------
# Makefile Options
# ----------------------------

NAME = HDTR
ICON = icon.png
DESCRIPTION = "Wallpapers"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
